INSERT INTO UTILISATEUR VALUES(001,'COIRON','CHRISTOPHE','christophe.coiron@gmail.com','france','lyon','69009','');
INSERT INTO UTILISATEUR VALUES(002,'SEVENIER','LOLA','lola.sev@gmail.com','france','lyon','69009','');

INSERT INTO CENTREINTERET  VALUES(001,'C#');
INSERT INTO CENTREINTERET  VALUES(002,'PHP');
INSERT INTO CENTREINTERET  VALUES(003,'TDD');

INSERT INTO PROFIL VALUES(001,001,003);/*coiron aime  tdd*/
INSERT INTO PROFIL VALUES(001,002,001);/*lola aime  c#*/
